import "@/styles/app.css";
import type { Metadata } from "next";
import { Work_Sans } from "next/font/google";

// If loading a variable font, you don't need to specify the font weight
const workSans = Work_Sans({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={workSans.className}>{children}</body>
    </html>
  );
}
